# Nouveaux Ã©lÃ©ments
data = [
    ' des cartes et systèmes électroniques',
    'agence de communication',
    'agence de voyage',
    'assurance',
    'Assurance/Consulting',
    'automobile',
    'avocat',
    'banque/assurance',
    'bureautique',
    'centre dappele',
    'consulting',
    'decoration',
    'domaine electricite',
    'equipement',
    'equipement Electriques',
    'équipement pour le bâtiment',
    'expertise',
    'formattion',
    'industrie',
    'informatique',
    'kiosque',
    'laboratoire',
    'mecanique',
    'medical',
    'meubles',
    'société',
    'societe de livraison',
    'societe de vetements',
    'transit',
    'vente different produit',
]
