recipe: default.v1
language: fr
encoding: "utf-8"  # Spécifiez l'encodage UTF-8
pipeline:
- name: SpacyNLP
  model: "fr_core_news_md"  # Remplacez "fr_core_news_md" par le nom du modèle SpaCy en français que vous souhaitez utiliser
- name: SpacyTokenizer
- name: SpacyFeaturizer
- name: RegexFeaturizer
- name: CRFEntityExtractor  # Composant NER fourni par Rasa
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4
- name: DIETClassifier
  epochs: 130
  constrain_similarities: true
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 120
  constrain_similarities: true
# - name: FallbackClassifier
#   threshold: 0.6  # Modifier ce seuil selon vos besoins
#   ambiguity_threshold: 0.1
# assistant_id: 20240216-164319-tractable-convergence

policies:
- name: MemoizationPolicy
- name: RulePolicy
- name: UnexpecTEDIntentPolicy
  max_history: 2
  epochs: 120
- name: TEDPolicy
  max_history: 2
  epochs: 120
  constrain_similarities: true
assistant_id: 20240423-212904-miniature-pintail
